### ISSUE TITLE
Best way to test the npm package locally?

### ISSUE THREAD

**Issue by javed24** [leonardofaria/eslint-config-leozera#43]
Hi there, 

I was following along your blog [post](https://www.freecodecamp.org/news/creating-your-own-eslint-config-package/). I'm towards the end of it where you run `npm install /Users/leonardo/path/to/eslint-config-test`. Upon doing this I'm getting a bunch of warnings on my JS project (the one that consumes the package) on the peer deps. 

A little about what I'm doing - I made sure to add `peerDependencies` to my npm package, similar to what you're doing [here](https://github.com/leonardofaria/eslint-config-leozera/blob/master/package.json). The JS project that consumes this package has older versions of these dependencies (`eslint`, `eslint-config-prettier`, `eslint-plugin-import` etc.). I did notice that you and wesbos both used `npx install-peerdeps --dev` which I believe works on published npm packages? I'm guessing this because when I ran `npx install-peerdeps /Users/path/to/eslint-config-mypackage` I got the following:

```
install-peerdeps v3.0.3
ERR undefined
```

Any suggestions as to what would be the best way to install these peer dependencies? (not sure if this is the best place to ask this, apologies if not)

**Comment by leonardofaria** [comment]
Hi @javed24 

Sorry for the delay here. Totally missed this issue.

Instead of using `npx`, you can just use `npm install` or `yarn install` with the packages listed in the `package.json` file.
